# Generated by Django 5.2.3 on 2025-07-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pasajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=5)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.avion')),
            ],
        ),
    ]
