# Generated by Django 5.2.3 on 2025-07-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=100)),
                ('fecha_emision', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.reserva')),
            ],
        ),
    ]
